[build]
builder = "DOCKERFILE"
dockerfilePath = "openhedge-core/Dockerfile"

[deploy]
preDeployCommand = ["python -m openhedge_core.setup_qdrant"]
startCommand = "python -m openhedge_core.server"
healthcheckPath = "/health"
healthcheckTimeout = 300
numReplicas = 1
restartPolicyType = "ON_FAILURE"
